name = "KrestMC"
author = "krestgg"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca1cc76a1f9c8d26db8b2ba5e08d5fe77f2ed819f63dd38025e1c52093281c77"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
