name = "KrestMC"
author = "krestgg"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ecf69d83c3703967c21f7b71be2227ee25a0bea9f499b46ca16fdb22af9921b"

[versions]
fabric = "0.19.2"
minecraft = "1.21.8"
